### ISSUE TITLE
Run errors on local machine

### ISSUE THREAD

**Issue by Fortiskrito** [dmlc/wormhole#64]
when i run the command `tracker/dmlc_local.py -n 1 -s 1 bin/linear.dmlc learn/linear/guide/demo.conf` i got following results:

> 2016-02-11 15:01:01,856 INFO start listen on ::1:9091
> F0211 15:01:01.863415  9390 van.cc:48] Check failed: !zmq_socket_monitor( senders_[scheduler_.id()], "inproc://monitor", ZMQ_EVENT_ALL) 
> F0211 15:01:01.863451  9392 van.cc:48] Check failed: !zmq_socket_monitor( senders_[scheduler_.id()], "inproc://monitor", ZMQ_EVENT_ALL) 
> *** Check failure stack trace: ***
> *** Check failure stack trace: ***
>     @     0x7f1186763e6d  (unknown)
>     @     0x7fa56a478e6d  (unknown)
>     @     0x7f1186765ced  (unknown)
>     @     0x7f1186763a5c  (unknown)
>     @     0x7fa56a47aced  (unknown)
>     @     0x7f118676663e  (unknown)
> F0211 15:01:01.863739  9385 manager.cc:173] Check failed: van_.Connect(node) 
>     @           0x474171  ps::Van::Init()
> *** Check failure stack trace: ***
>     @     0x7fa56a478a5c  (unknown)
>     @           0x47926c  ps::Manager::Init()
>     @           0x46d748  ps::Postoffice::Run()
>     @     0x7fa56a47b63e  (unknown)
>     @           0x408681  main
>     @     0x7f0974fb2e6d  (unknown)
>     @           0x474171  ps::Van::Init()
>     @     0x7f0974fb4ced  (unknown)
>     @     0x7f1185765b15  __libc_start_main
>     @           0x47926c  ps::Manager::Init()
>     @     0x7f0974fb2a5c  (unknown)
>     @           0x46d748  ps::Postoffice::Run()
>     @     0x7f0974fb563e  (unknown)
>     @           0x409a21  (unknown)
>     @           0x408681  main
>     @           0x47903a  ps::Manager::AddNode()
>     @           0x4793c3  ps::Manager::Init()
>     @           0x46d748  ps::Postoffice::Run()
>     @     0x7fa56947ab15  __libc_start_main
>     @           0x408681  main
>     @           0x409a21  (unknown)
>     @     0x7f0973fb4b15  __libc_start_main
>     @           0x409a21  (unknown)
> bash: line 9:  9392 Aborted                 (core dumped) bin/linear.dmlc learn/linear/guide/demo.conf
> bash: line 9:  9390 Aborted                 (core dumped) bin/linear.dmlc learn/linear/guide/demo.conf
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
>     self.run()
>   File "/usr/lib64/python2.7/threading.py", line 764, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/xiaxin/Documents/parameter_application/wormhole/repo/dmlc-core/tracker/tracker.py", line 354, in <lambda>
>     self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
>   File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command 'bin/linear.dmlc learn/linear/guide/demo.conf ' returned non-zero exit status -6
> 
> 
to find the problem i then ran the command : `bin/linear.dmlc learn/linear/guide/demo.conf` and got the messages below:

> F0211 15:01:30.553581  9454 manager.cc:55] Timeout (10 sec) to wait all other nodes initialized. See commmets for more information
> *** Check failure stack trace: ***
>     @     0x7fc8faf78e6d  (unknown)
>     @     0x7fc8faf7aced  (unknown)
>     @     0x7fc8faf78a5c  (unknown)
>     @     0x7fc8faf7b63e  (unknown)
>     @           0x475c42  ps::Manager::Run()
>     @           0x46d939  ps::Postoffice::Run()
>     @           0x408681  main
>     @     0x7fc8f9f7ab15  __libc_start_main
>     @           0x409a21  (unknown)
> Aborted (core dumped)
> 
Every example get the same error, local environment is centos 7.

**Comment by Fortiskrito** [comment]
i find the problem is that ip address is not correct. I assign the host ip directly by adding `hostIP = "127.0.0.1"` in tracker.py, submit, 374. and it gets work!
